apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: business-application-service
spec:
  adminPassword: redhat
  adminUser: admin
  anonymous: true
  basicAuth: true
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: redhat
      admin_user: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  disableLoginForm: true
  ingress:
    enabled: true