apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: business-application-service
spec:
  podMonitorSelector: {}
  probeSelector: {}
  replicas: 2
  ruleSelector: {}
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: rhdm