kind: Service
apiVersion: v1
metadata:
  annotations:
    description: RHDM Prometheus metrics exposed
  name: rhdm-app-metrics
  labels:
    app: business-application-service
    metrics: rhdm
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: business-application-service
    group: com.redhat.demos
    provider: jkube
  type: ClusterIP