apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhdm-service-monitor
  labels:
    app: business-application-service
    team: rhdm
spec:
  endpoints:
    - basicAuth:
        password:
          key: password
          name: metrics-secret
        username:
          key: username
          name: metrics-secret
      interval: 30s
      path: /rest/metrics
      port: web
  selector:
    matchLabels:
      metrics: rhdm
